
git fetch origin
git checkout -b "rashtinjei-patch-1" "origin/rashtinjei-patch-1"
git merge "master"

name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

git checkout "master"
git merge --no-ff "rashtinjei-patch-1"
git push origin "master"
